name: Publish Minor Version to Docker
on:
  workflow_dispatch:


jobs:
  build-publish-docker:
    uses: IABTechLab/uid2-shared-actions/.github/workflows/shared-publish-docker-versioned.yaml@v2.8
    with: 
      cloud_provider: 'default'
      release_type: 'Minor'
    secrets: inherit
