name: Publish Patch to Docker
on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'The tag to apply to the Docker file'
        type: string

jobs:
  build-publish-docker:
    uses: IABTechLab/uid2-shared-actions/.github/workflows/shared-publish-docker-versioned.yaml@v2.4
    with: 
      tag: ${{ inputs.tag }}
      cloud_provider: 'default'
      release_type: 'Patch'
    secrets: inherit
